services:
  pick_and_place:
    build:
      context: .
      dockerfile: Dockerfile
    image: pick_and_place
    container_name: pick_and_place
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=72
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - USE_SIM=${USE_SIM:-true}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /dev:/dev
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      source /ros2_ws/install/setup.bash &&
      ros2 launch pick_and_place pick_and_place.launch.py use_sim:=$$USE_SIM
      "
