obstacles:

  # =========================
  # BOX
  # =========================
  - id: boxes
    type: box
    frame: world
    size: [0.6, 0.7, 0.36]      # x, y, z
    position: [-0.86, 0.38, 0.2]
    orientation: [0.0, 0.0, 0.0, 1.0]

  - id: table
    type: box
    frame: world
    size: [1.0, 1.0, 0.2]      # x, y, z
    position: [0.0, 0.0, -0.100001]
    orientation: [0.0, 0.0, 0.0, 1.0]

  - id: obstacle
    type: box
    frame: world
    size: [0.5, 0.2, 0.05]      # x, y, z
    position: [-0.96, 0.21, 0.8]
    orientation: [0.0, 0.0, 0.0, 1.0]

  - id: cell
    type: box
    frame: world
    size: [3.0, 0.1, 4.0]      # x, y, z
    position: [-0.18, 1.28, 0.8]
    orientation: [0.0, 0.0, 0.0, 1.0]

  # # =========================
  # # SPHERE
  # # =========================
  # - id: ball
  #   type: sphere
  #   frame: world
  #   radius: 0.15
  #   position: [0.2, -0.5, 0.15]
  #   orientation: [0.0, 0.0, 0.0, 1.0]

  # # =========================
  # # CYLINDER
  # # =========================
  # - id: pillar
  #   type: cylinder
  #   frame: world
  #   radius: 0.12
  #   height: 1.2
  #   position: [1.0, 0.4, 0.6]
  #   orientation: [0.0, 0.0, 0.0, 1.0]

  # # =========================
  # # MESH
  # # =========================
  # - id: engine_block
  #   type: mesh
  #   frame: world
  #   resource: package://pick_and_place/meshes/engine_block.stl
  #   scale: 1.0
  #   position: [-0.4, 0.3, 0.0]
  #   orientation: [0.0, 0.0, 0.0, 1.0]
